# English -> standard French for every visible string on the site.
# Names of products, games and places that stay the same are not listed.
N = ' '  # non-breaking space before : ; ! ? and inside numbers, as French typography wants
FR = {
 # ---------- shared ----------
 'Homelabber, CTO and sysadmin, Minecraft network manager, and casual PC gamer.': 'Homelabber, CTO et administrateur système, gestionnaire de réseau Minecraft et joueur PC occasionnel.',
 'Main': 'Principal',
 'Home': 'Accueil',
 'Setup': 'Poste de jeu',
 'Now': 'En ce moment',
 'TehZombiJesus · tehzombijesus.ca': 'TehZombiJesus · tehzombijesus.ca',

 # ---------- home ----------
 'TehZombiJesus avatar': 'Avatar de TehZombiJesus',
 'Click me': 'Clique-moi',
 "I run servers, manage a Minecraft network, and keep a homelab that's always one upgrade away from finished.": "Je fais rouler des serveurs, je gère un réseau Minecraft et j'entretiens un homelab qui est toujours à une mise à niveau d'être terminé.",
 'CTO and sysadmin by role, tinkerer by habit, casual gamer after hours.': "CTO et administrateur système de métier, bricoleur par habitude, joueur occasionnel après les heures.",
 'Right now:': 'En ce moment' + N + ':',
 'keeping the servers alive|building The Crypt|planning a 57-inch setup|upgrading the homelab, again|playing ARAM, just for fun':
   'je garde les serveurs en vie|je bâtis la Crypte|je planifie un poste de 57 pouces|je mets à niveau le homelab, encore|je joue en ARAM, juste pour le plaisir',
 'keeping the servers alive': 'je garde les serveurs en vie',
 'Join the Crypt': 'Rejoindre la Crypte',
 'See the homelab': 'Voir le homelab',
 'Find me': 'Me trouver',
 'Same name everywhere: TehZombiJesus.': 'Le même nom partout' + N + ': TehZombiJesus.',
 'The Crypt': 'La Crypte',
 'My Discord server': 'Mon serveur Discord',
 'Minecraft network, SMP and SkyPvP': 'Réseau Minecraft, SMP et SkyPvP',
 'About me': 'À propos de moi',
 'The short version.': 'La version courte.',
 'Cartoon version of TehZombiJesus': 'Version dessin animé de TehZombiJesus',
 'years old': 'ans',
 'Eastern time': "Heure de l'Est",
 "I'm Kevin, better known online as TehZombiJesus. I'm the person who ends up running the servers: setting them up, keeping them online, and figuring out why they stopped.":
   "Je m'appelle Kevin, mieux connu en ligne sous le nom de TehZombiJesus. Je suis celui qui finit toujours par s'occuper des serveurs" + N + ": les installer, les garder en ligne et comprendre pourquoi ils ont arrêté.",
 "These days that means being CTO and systems administrator at Nox Interactive, managing the Ruenix Minecraft network, and a homelab at home that's slowly turning into a small datacentre. I'm not a developer. My side of things is infrastructure, coordination, and keeping communities organized.":
   "Ces temps-ci, ça veut dire être CTO et administrateur système chez Nox Interactive, gérer le réseau Minecraft Ruenix, et entretenir à la maison un homelab qui devient tranquillement un petit centre de données. Je ne suis pas développeur. Mon rôle, c'est l'infrastructure, la coordination et l'organisation des communautés.",
 "When it's all running, I'm usually in a game, strictly for fun.": "Quand tout roule, je suis habituellement dans un jeu, juste pour le plaisir.",
 'What I work on': 'Ce sur quoi je travaille',
 'Infrastructure, communities, and a server rack that keeps growing.': "De l'infrastructure, des communautés et une baie de serveurs qui ne cesse de grandir.",
 'CTO and Systems Administrator': 'CTO et administrateur système',
 'Leading the technical side of a small software company: infrastructure, project coordination, and keeping our systems and services running.':
   "Je dirige le côté technique d'une petite entreprise de logiciels" + N + ": l'infrastructure, la coordination des projets et le bon fonctionnement de nos systèmes et services.",
 'Manager': 'Gestionnaire',
 'A Minecraft network with SMP and SkyPvP servers. I lead the staff team and run the Discord community.': "Un réseau Minecraft avec des serveurs SMP et SkyPvP. Je dirige l'équipe de modération et j'anime la communauté Discord.",
 'About Ruenix': 'À propos de Ruenix',
 'Ongoing, forever': 'En cours, pour toujours',
 'Proxmox and TrueNAS at home, self-hosting my photos and files, with everything behind Cloudflare.': "Proxmox et TrueNAS à la maison, j'héberge moi-même mes photos et mes fichiers, le tout derrière Cloudflare.",
 'Tour the homelab': 'Visiter le homelab',
 'Discord admin': 'Admin Discord',
 'Off the clock': 'Après le travail',
 'PC gamer, controller in hand, strictly for fun. No ranked, no sweat.': 'Joueur PC, manette en main, juste pour le plaisir. Pas de classé, pas de stress.',
 'Better with friends': 'Mieux entre amis',
 'Whenever chaos is needed': 'Quand ça prend du chaos',
 'Open-world stealth': 'Infiltration en monde ouvert',
 'ARAM only': 'ARAM seulement',
 'The next setup': 'Le prochain poste de jeu',
 'Being planned, piece by piece.': 'En planification, morceau par morceau.',
 'Desk': 'Bureau',
 'Main screen': 'Écran principal',
 'Samsung Odyssey Neo G9, 57"': 'Samsung Odyssey Neo G9, 57' + N + 'po',
 'Top row': 'Rangée du haut',
 'Three 22" monitors': 'Trois écrans de 22' + N + 'po',
 'GPU': 'Carte graphique',
 'CPU': 'Processeur',
 'Full setup': 'Le poste au complet',
 'How I play': 'Comment je joue',
 'Controller, always': 'Manette, toujours',
 'Xbox pad, even on PC': 'Manette Xbox, même sur PC',
 'Never ranked': 'Jamais en classé',
 'Games are for fun': 'Les jeux, c\'est pour s\'amuser',
 '120 FPS is plenty': '120 IPS, c\'est assez',
 'No chasing numbers': 'Pas de course aux chiffres',
 'Bass up': 'Basses à fond',
 'Headset EQ set to rumble': "L'égaliseur du casque réglé pour faire vibrer",
 'Play with me': 'Joue avec moi',
 'The Minecraft network I manage.': 'Le réseau Minecraft que je gère.',
 'Ruenix crest': 'Blason de Ruenix',
 'A Minecraft network with Survival (SMP) and SkyPvP servers. English-speaking community, friendly staff, and more game modes on the way.':
   "Un réseau Minecraft avec des serveurs Survie (SMP) et SkyPvP. Communauté anglophone, équipe sympathique et d'autres modes de jeu à venir.",
 'Opening soon': 'Ouverture bientôt',
 'Join the Discord to hear first': 'Rejoins le Discord pour être le premier informé',
 'Join the Discord': 'Rejoindre le Discord',
 'More about Ruenix': 'En savoir plus sur Ruenix',
 'Get in touch': 'Me contacter',
 'The Crypt, my Discord server, is the fastest way to reach me. For anything more formal, email works too.':
   "La Crypte, mon serveur Discord, est le moyen le plus rapide de me joindre. Pour quelque chose de plus officiel, le courriel fonctionne aussi.",
 'Copy email': 'Copier le courriel',

 # ---------- homelab ----------
 'Homelab | TehZombiJesus': 'Homelab | TehZombiJesus',
 'The TehZombiJesus homelab: Proxmox, TrueNAS, self-hosted services, and the hardware behind them.': 'Le homelab de TehZombiJesus' + N + ': Proxmox, TrueNAS, les services autohébergés et le matériel derrière.',
 'The rack that keeps growing': 'La baie qui ne cesse de grandir',
 "What I self-host at home, the hardware it runs on, and where it's headed. It's never finished, and that's the fun part.":
   "Ce que j'héberge moi-même à la maison, le matériel qui le fait rouler et la suite des choses. Ce n'est jamais fini, et c'est ça le plaisir.",
 "What's running": 'Ce qui roule',
 'Everything lives in virtual machines and containers on one Proxmox host, with storage handled by TrueNAS.': 'Tout vit dans des machines virtuelles et des conteneurs sur un seul hôte Proxmox, et TrueNAS gère le stockage.',
 'Hypervisor': 'Hyperviseur',
 'The foundation. Every service runs in its own VM or container, so one breaking never takes the rest with it.': "La fondation. Chaque service roule dans sa propre VM ou son propre conteneur, alors si l'un plante, il n'entraîne pas les autres.",
 'Storage': 'Stockage',
 'ZFS storage for everything else: media, backups, and shares.': 'Le stockage ZFS pour tout le reste' + N + ': médias, sauvegardes et partages.',
 'App deployment': "Déploiement d'applications",
 'A self-hosted platform for spinning up apps and databases. Its built-in proxy gives each one its own address with automatic HTTPS.':
   "Une plateforme autohébergée pour lancer des applications et des bases de données. Son proxy intégré donne à chacune sa propre adresse avec HTTPS automatique.",
 'Photos': 'Photos',
 'My own Google Photos: phone backups, albums, and search, kept on my hardware.': 'Mon propre Google Photos' + N + ': sauvegardes du téléphone, albums et recherche, gardés sur mon matériel.',
 'Files': 'Fichiers',
 'File sync and sharing across devices, without a third-party cloud.': "Synchronisation et partage de fichiers entre mes appareils, sans nuage d'un tiers.",
 'Trying out': "À l'essai",
 'A media server for the movie and TV library.': 'Un serveur multimédia pour la collection de films et de séries.',
 'Status monitoring that pings every service and warns when something goes down.': "Une surveillance qui vérifie chaque service et avertit quand quelque chose tombe.",
 'Edge and DNS': 'Périphérie et DNS',
 'DNS, protection, and secure access, including this website.': 'DNS, protection et accès sécurisé, y compris pour ce site.',
 'How it connects': 'Comment tout se connecte',
 'From the internet to the drives. Hover or tap any box to see what it does.': "D'Internet jusqu'aux disques. Survole ou touche une boîte pour voir à quoi elle sert.",
 'Map of the homelab: Cloudflare and the fibre connection lead to the UniFi gateway, which feeds one Proxmox host running TrueNAS, Coolify, the apps and Uptime Kuma, with TrueNAS managing a fast NVMe pool and a RAIDZ2 media pool. An off-site server connects through Cloudflare.':
   "Carte du homelab" + N + ": Cloudflare et la connexion fibre mènent à la passerelle UniFi, qui alimente un hôte Proxmox faisant rouler TrueNAS, Coolify, les applications et Uptime Kuma. TrueNAS gère un pool NVMe rapide et un pool multimédia en RAIDZ2. Un serveur hors site se connecte par Cloudflare.",
 'Proxmox host': 'Hôte Proxmox',
 'One machine running everything below, each service in its own virtual machine or container. If one breaks, the rest keep going.': "Une seule machine qui fait rouler tout ce qui suit, chaque service dans sa propre machine virtuelle ou son propre conteneur. Si l'un plante, le reste continue.",
 'One machine. Every service in its own VM or container.': 'Une machine. Chaque service dans sa propre VM ou son conteneur.',
 'DNS for my domains, protection in front of everything public, and secure access from outside. This website runs on it too.': "Le DNS de mes domaines, une protection devant tout ce qui est public et un accès sécurisé de l'extérieur. Ce site roule dessus aussi.",
 'DNS · protection': 'DNS · protection',
 'Fibre': 'Fibre',
 'Multi-gig fibre, planned at 3 Gbps, so uploads and remote access are never the bottleneck.': 'Fibre multigigabit, prévue à 3' + N + 'Gb/s, pour que les envois et l\'accès à distance ne soient jamais le goulot d\'étranglement.',
 '3 Gbps, planned': '3' + N + 'Gb/s, prévu',
 'Off-site server': 'Serveur hors site',
 'A rented dedicated server running Proxmox for work projects. Kept separate from home, and reached through Cloudflare.': "Un serveur dédié loué qui fait rouler Proxmox pour des projets de travail. Gardé séparé de la maison et accessible par Cloudflare.",
 'Work projects': 'Projets de travail',
 'UniFi gateway': 'Passerelle UniFi',
 'UniFi Cloud Gateway Fiber: routing and firewall for the whole network. Chosen over a DIY pfSense box for easier day-to-day management.':
   "UniFi Cloud Gateway Fiber" + N + ": routage et pare-feu pour tout le réseau. Choisie plutôt qu'une boîte pfSense maison pour une gestion plus simple au quotidien.",
 'Router · firewall': 'Routeur · pare-feu',
 'Runs ZFS and owns the hard drives directly through the HBA. Serves storage to everything else.': 'Fait rouler ZFS et contrôle les disques durs directement par le HBA. Fournit le stockage à tout le reste.',
 'Fast pool': 'Pool rapide',
 'Mirrored NVMe drives. VMs, containers and apps live here so they stay fast.': 'Disques NVMe en miroir. Les VM, les conteneurs et les applications vivent ici pour rester rapides.',
 'Fast': 'Rapide',
 'Media pool': 'Pool multimédia',
 'WD Red Pro drives in RAIDZ2, for movies and TV only. Any two drives can fail without losing anything.': "Des disques WD Red Pro en RAIDZ2, seulement pour les films et les séries. N'importe quels deux disques peuvent lâcher sans rien perdre.",
 'Media': 'Médias',
 'A self-hosted app platform: spins up apps and databases, each with its own address and automatic HTTPS.': "Une plateforme d'applications autohébergée" + N + ": lance des applications et des bases de données, chacune avec sa propre adresse et HTTPS automatique.",
 'App platform': "Plateforme d'applications",
 'Photo and video backups from phones, with albums and search. My own Google Photos.': 'Sauvegardes des photos et vidéos des téléphones, avec albums et recherche. Mon propre Google Photos.',
 'Immich · photos': 'Immich · photos',
 'Seafile · files': 'Seafile · fichiers',
 'A media server for the movie and TV library. Still being tried out.': "Un serveur multimédia pour la collection de films et de séries. Encore à l'essai.",
 'Jellyfin · media': 'Jellyfin · médias',
 'Pings every service around the clock and warns me when something goes down. Still being tried out.': "Vérifie chaque service jour et nuit et m'avertit quand quelque chose tombe. Encore à l'essai.",
 'Keeps an eye on everything': "Garde l'œil sur tout",
 'Hover or tap a box': 'Survole ou touche une boîte',
 'to see what it does.': 'pour voir à quoi elle sert.',
 'The next server': 'Le prochain serveur',
 "A rebuild that's being planned in stages, so storage can grow without starting over.": 'Une reconstruction planifiée par étapes, pour que le stockage puisse grandir sans tout recommencer.',
 'Build plan': 'Plan de montage',
 'Parts chosen, and why each one.': 'Les pièces choisies, et pourquoi chacune.',
 'Built-in Quick Sync handles video transcoding for Jellyfin without a separate graphics card. Plenty of cores for the VMs, and low power at idle.':
   "Quick Sync intégré gère le transcodage vidéo pour Jellyfin sans carte graphique séparée. Plein de cœurs pour les VM, et une faible consommation au repos.",
 'Board': 'Carte mère',
 "A workstation board, because it supports ECC memory, which regular desktop boards don't. Room for the HBA and the NVMe drives too.":
   "Une carte de station de travail, parce qu'elle prend en charge la mémoire ECC, contrairement aux cartes de bureau ordinaires. De la place pour le HBA et les disques NVMe aussi.",
 'Memory': 'Mémoire',
 '64 GB ECC': '64' + N + 'Go ECC',
 'ECC catches memory errors before they reach the data. 64 GB covers every VM plus ZFS caching, with slots free to add more.':
   "L'ECC attrape les erreurs de mémoire avant qu'elles touchent les données. 64" + N + "Go suffisent pour toutes les VM et le cache de ZFS, avec des emplacements libres pour en ajouter.",
 'Cooler': 'Refroidisseur',
 'Quiet and dependable. An air cooler has no pump to fail on a machine that runs 24/7.': "Silencieux et fiable. Un refroidisseur à air n'a pas de pompe qui peut lâcher sur une machine qui roule 24" + N + "h sur 24.",
 'PSU': 'Bloc d\'alimentation',
 'Enough power for a case full of hard drives spinning up at the same time, and silent at low load.': 'Assez de puissance pour un boîtier plein de disques durs qui démarrent en même temps, et silencieux à faible charge.',
 'Case': 'Boîtier',
 'Room for lots of drives, and sound-dampened panels so a box full of disks stays quiet.': "De la place pour beaucoup de disques, et des panneaux insonorisés pour qu'un boîtier plein de disques reste silencieux.",
 'Controller': 'Contrôleur',
 '16-port HBA': 'HBA 16 ports',
 'Connects far more drives than the motherboard can, and hands them straight to TrueNAS, which ZFS needs to work properly.': "Branche bien plus de disques que la carte mère peut en prendre, et les donne directement à TrueNAS, ce dont ZFS a besoin pour bien fonctionner.",
 'Boot': 'Démarrage',
 '2× 480 GB SSD, mirrored': '2 SSD de 480' + N + 'Go en miroir',
 'If one boot drive dies, the server keeps running on the other.': "Si un disque de démarrage meurt, le serveur continue de rouler sur l'autre.",
 '2× 4 TB NVMe, mirrored': '2 NVMe de 4' + N + 'To en miroir',
 'VMs, containers and apps run from fast flash. Mirrored, so one drive can fail without losing anything.': 'Les VM, les conteneurs et les applications roulent sur de la mémoire flash rapide. En miroir, alors un disque peut lâcher sans rien perdre.',
 '7× WD Red Pro 20 TB, RAIDZ2 to start': '7 WD Red Pro de 20' + N + 'To, en RAIDZ2 pour commencer',
 'Where the movies and TV live. NAS-grade drives made to run all day, added in batches as the library grows.': 'Là où vivent les films et les séries. Des disques de qualité NAS faits pour rouler toute la journée, ajoutés par lots à mesure que la collection grandit.',
 'UPS': 'Onduleur',
 'Rides through short outages and gives time to shut down cleanly in a long one, so no write is ever lost halfway.': "Tient le coup pendant les courtes pannes et donne le temps de tout fermer proprement pendant une longue, pour qu'aucune écriture ne soit perdue à mi-chemin.",
 "Why it's built this way": 'Pourquoi il est conçu ainsi',
 'A server that runs 24/7 at home has three jobs: keep the data safe, grow without a rebuild, and stay quiet enough to live with. Every choice comes back to one of those.':
   "Un serveur qui roule 24" + N + "h sur 24 à la maison a trois tâches" + N + ": garder les données en sécurité, grandir sans reconstruction et rester assez silencieux pour vivre avec. Chaque choix revient à l'une d'elles.",
 'Two drives can fail, and nothing is lost': 'Deux disques peuvent lâcher, et rien ne se perd',
 "The media pool uses RAIDZ2: two drives' worth of space holds parity, so any two can die at the same time and the pool keeps running while they're replaced. That costs raw capacity, but on drives this big a rebuild takes days, and a second failure during a rebuild is the real risk. Peace of mind over extra terabytes.":
   "Le pool multimédia utilise le RAIDZ2" + N + ": l'espace de deux disques sert à la parité, alors n'importe quels deux disques peuvent mourir en même temps et le pool continue de rouler pendant qu'on les remplace. Ça coûte de la capacité brute, mais sur des disques aussi gros, une reconstruction prend des jours, et une deuxième panne pendant la reconstruction est le vrai risque. La tranquillité d'esprit avant les téraoctets en plus.",
 'Grows in stages, never starts over': 'Grandit par étapes, sans jamais recommencer',
 'The case, controller and power supply are sized for the full drive count from day one. Drives get added in batches as the library grows, instead of paying for empty space up front or migrating everything to a new box later.':
   "Le boîtier, le contrôleur et l'alimentation sont choisis pour le nombre total de disques dès le premier jour. Les disques s'ajoutent par lots à mesure que la collection grandit, au lieu de payer d'avance pour de l'espace vide ou de tout migrer vers une nouvelle machine plus tard.",
 'Fast storage and big storage, kept apart': 'Le stockage rapide et le gros stockage, séparés',
 'VMs, containers and apps live on mirrored NVMe, so they stay quick no matter what the hard drives are doing. The hard drives only hold movies and TV, which need space, not speed.':
   "Les VM, les conteneurs et les applications vivent sur du NVMe en miroir, pour rester rapides peu importe ce que font les disques durs. Les disques durs gardent seulement les films et les séries, qui ont besoin d'espace, pas de vitesse.",
 'Safety net, not a full backup': 'Un filet de sécurité, pas une sauvegarde complète',
 "Everything on the media pool can be replaced, so RAIDZ2 is its protection. Backing up that many terabytes would double the cost of the storage for files that aren't irreplaceable.":
   "Tout ce qui est sur le pool multimédia peut être remplacé, alors le RAIDZ2 est sa protection. Sauvegarder autant de téraoctets doublerait le coût du stockage pour des fichiers qui ne sont pas irremplaçables.",
 'The data stays correct': 'Les données restent intactes',
 "ZFS checks every block it reads and repairs silent corruption from the redundant copy. ECC memory closes the last gap by catching errors in RAM before they're written to disk. 64 GB to start while memory prices are high, with slots free to add more.":
   "ZFS vérifie chaque bloc qu'il lit et répare la corruption silencieuse à partir de la copie redondante. La mémoire ECC ferme la dernière brèche en attrapant les erreurs en RAM avant qu'elles soient écrites sur le disque. 64" + N + "Go pour commencer pendant que la mémoire coûte cher, avec des emplacements libres pour en ajouter.",
 'Quiet, cool and boring': 'Silencieux, frais et ennuyant',
 'A sound-dampened case, a Noctua air cooler with no pump to fail, and a battery backup for outages. The goal is a server you forget is there.':
   "Un boîtier insonorisé, un refroidisseur à air Noctua sans pompe qui peut lâcher, et une batterie de secours pour les pannes. Le but" + N + ": un serveur qu'on oublie.",
 'Network': 'Réseau',
 'The plumbing that ties it together.': 'La plomberie qui relie le tout.',
 'Planned: 3 Gbps': 'Prévu' + N + ': 3' + N + 'Gb/s',
 "A multi-gig fibre connection, so remote access and uploads aren't the bottleneck.": "Une connexion fibre multigigabit, pour que l'accès à distance et les envois ne soient pas le goulot d'étranglement.",
 'Ubiquiti for routing and firewall, chosen over a DIY pfSense box for easier day-to-day management.': "Ubiquiti pour le routage et le pare-feu, choisi plutôt qu'une boîte pfSense maison pour une gestion plus simple au quotidien.",
 'Off-site': 'Hors site',
 'Dedicated server': 'Serveur dédié',
 'A rented dedicated server runs Proxmox for work projects, kept separate from home and all behind Cloudflare.': 'Un serveur dédié loué fait rouler Proxmox pour des projets de travail, séparé de la maison et entièrement derrière Cloudflare.',

 # ---------- setup ----------
 'Setup | TehZombiJesus': 'Poste de jeu | TehZombiJesus',
 'The TehZombiJesus gaming setup: the monitor layout, the full next build, desk and mounting, peripherals, and the rules behind it.': "Le poste de jeu de TehZombiJesus" + N + ": la disposition des écrans, le prochain PC au complet, le bureau et les supports, les périphériques et les règles derrière tout ça.",
 'The battlestation': 'La station de combat',
 'A 57" super ultrawide, three screens above it, and a PC hanging under a standing desk. Every part chosen to last.': "Un écran super ultralarge de 57" + N + "po, trois écrans au-dessus et un PC suspendu sous un bureau assis-debout. Chaque pièce choisie pour durer.",
 'The layout': 'La disposition',
 'Everything is mounted to the desk, so the whole setup rises and lowers together when I switch between sitting and standing.': "Tout est fixé au bureau, alors l'ensemble monte et descend d'un bloc quand je passe de assis à debout.",
 'Front view of the desk: a 57-inch curved monitor on an arm, three 22-inch monitors on two poles above it ending flush with its edges, and the PC hanging under the desk':
   "Vue de face du bureau" + N + ": un écran incurvé de 57 pouces sur un bras, trois écrans de 22 pouces sur deux poteaux au-dessus qui finissent pile avec ses bords, et le PC suspendu sous le bureau",
 'angled ~31°': 'incliné d\'env. 31°',
 'Odyssey Neo G9 57"': 'Odyssey Neo G9 57' + N + 'po',
 'under desk': 'sous le bureau',
 'MAGNUS Pro XL, about 1.78 m wide': 'MAGNUS Pro XL, environ 1,78' + N + 'm de large',
 'Vertical Monitor Stands': "Supports d'écran verticaux",
 'Two poles about 20 cm either side of centre, tall enough to lift the top row clear of the 57&quot;.': "Deux poteaux à environ 20" + N + "cm de chaque côté du centre, assez hauts pour soulever la rangée du haut au-dessus du 57" + N + "po.",
 'Turned in about 31° so it follows the curve of the 57&quot; below. Chat, Discord, a guide.': "Tourné vers l'intérieur d'environ 31° pour suivre la courbe du 57" + N + "po en dessous. Clavardage, Discord, un guide.",
 'Left 22"': '22' + N + 'po de gauche',
 'Straight above the middle of the 57&quot;. Stream, browser, or whatever needs watching.': "Juste au-dessus du milieu du 57" + N + "po. Un stream, le navigateur ou tout ce qu'il faut surveiller.",
 'Centre 22"': '22' + N + 'po du centre',
 'Mirror of the left screen, turned in to match the curve. Monitoring and music.': "Le reflet de l'écran de gauche, tourné vers l'intérieur pour suivre la courbe. Surveillance et musique.",
 'Right 22"': '22' + N + 'po de droite',
 "Two 4K screens' worth of pixels in one curved panel, 240 Hz, on the Heavy Duty arm. The main event.": "L'équivalent de deux écrans 4K dans une seule dalle incurvée, 240" + N + "Hz, sur le bras Heavy Duty. La pièce maîtresse.",
 'Hangs under the desk on the Premium PC Mount: off the floor, away from dust, and it moves with the desk.': "Suspendu sous le bureau sur le Premium PC Mount" + N + ": loin du plancher et de la poussière, et il bouge avec le bureau.",
 'Motorized sit-stand desk, about 1.78 m wide. Everything above and below rides up and down with it.': "Bureau assis-debout motorisé, environ 1,78" + N + "m de large. Tout ce qui est au-dessus et en dessous monte et descend avec lui.",
 'Hover a part': 'Survole une pièce',
 'Front view, roughly to scale. The outer screens look narrower because they turn in toward you. The dashed lines show the top row ending flush with the edges of the 57".':
   "Vue de face, à peu près à l'échelle. Les écrans des côtés ont l'air plus étroits parce qu'ils sont tournés vers toi. Les lignes pointillées montrent la rangée du haut qui finit pile avec les bords du 57" + N + "po.",
 'Samsung Odyssey Neo G9 57"': 'Samsung Odyssey Neo G9 57' + N + 'po',
 'Dual 4K super ultrawide, mini-LED, 240 Hz, 1000R curve. Mounted on the MAGNUS Heavy Duty arm.': "Super ultralarge double 4K, mini-LED, 240" + N + "Hz, courbure 1000R. Fixé sur le bras MAGNUS Heavy Duty.",
 'Three 22" screens above': 'Trois écrans de 22' + N + 'po au-dessus',
 'Thin bezels, 1080p. The outer two turn in about 31° to follow the curve below.': "Bordures minces, 1080p. Les deux des côtés sont tournés d'environ 31° pour suivre la courbe en dessous.",
 'Two Vertical Monitor Stands': "Deux supports d'écran verticaux",
 'About 20 cm either side of centre, tall enough to clear the 57".': "Environ 20" + N + "cm de chaque côté du centre, assez hauts pour dépasser le 57" + N + "po.",
 'PC under the desk': 'Le PC sous le bureau',
 'On the Secretlab Premium PC Mount, so the floor stays clear.': 'Sur le Premium PC Mount de Secretlab, pour garder le plancher dégagé.',
 'One special cable': 'Un câble spécial',
 'A VESA-certified DP80LL DisplayPort cable, the only kind that runs the 57" at full 240 Hz.': "Un câble DisplayPort DP80LL certifié VESA, le seul type qui fait rouler le 57" + N + "po à 240" + N + "Hz au complet.",
 'The next build': 'Le prochain PC',
 'Every part chosen, and why it made the cut. No RGB anywhere.': "Chaque pièce choisie, et pourquoi elle a été retenue. Aucun RGB nulle part.",
 'Core': 'Le cœur',
 '3D V-Cache is the best thing you can give a CPU for games. Top frame rates without running hot.': "Le 3D V-Cache est ce qu'on peut donner de mieux à un processeur pour les jeux. Des images par seconde au sommet sans chauffer.",
 'The 57" is basically two 4K screens side by side. It takes the strongest card made to drive it properly.': "Le 57" + N + "po, c'est en gros deux écrans 4K côte à côte. Ça prend la carte la plus puissante qui existe pour bien le faire rouler.",
 'Built for the X3D chips, with PCIe 5.0, Wi-Fi 7 and plenty of fast ports. Nothing to outgrow.': "Conçue pour les puces X3D, avec PCIe 5.0, Wi-Fi 7 et plein de ports rapides. Rien qui deviendra trop petit.",
 'RAM': 'Mémoire vive',
 '64 GB DDR5-6000, G.Skill': '64' + N + 'Go DDR5-6000, G.Skill',
 '6000 is the sweet spot for Ryzen. 64 GB so big games never run short, even with Discord and a browser open.': "6000, c'est le point idéal pour Ryzen. 64" + N + "Go pour que les gros jeux ne manquent jamais de mémoire, même avec Discord et un navigateur ouverts.",
 '2 TB WD Black, PCIe 5.0': 'WD Black de 2' + N + 'To, PCIe 5.0',
 'Games are huge now. The fastest drive goes where the games live.': "Les jeux sont énormes maintenant. Le disque le plus rapide va là où vivent les jeux.",
 '2 TB WD Black': 'WD Black de 2' + N + 'To',
 'Linux gets a drive of its own, with room for tools and projects.': "Linux a son propre disque, avec de la place pour les outils et les projets.",
 'Windows 11 and Ubuntu 26.04, each on its own drive': 'Windows 11 et Ubuntu 26.04, chacun sur son disque',
 'Windows for gaming, Linux for tinkering. Separate drives mean an update on one can never break the other.': "Windows pour jouer, Linux pour bricoler. Avec des disques séparés, une mise à jour sur l'un ne peut jamais briser l'autre.",
 'Power and cooling': 'Alimentation et refroidissement',
 'Seasonic 1600 W, Noctua Edition': 'Seasonic 1600' + N + 'W, édition Noctua',
 'The 5090 can spike hard. Lots of headroom keeps it cool, quiet and stable, and Titanium efficiency wastes less power.': "La 5090 peut avoir de gros pics. Beaucoup de marge le garde frais, silencieux et stable, et l'efficacité Titanium gaspille moins d'énergie.",
 'One of the best-performing coolers out there, quiet, and no RGB.': "Un des refroidisseurs les plus performants sur le marché, silencieux, et sans RGB.",
 'Lots of airflow for a 5090, room for a clean build, and a wood front instead of lights.': "Beaucoup de circulation d'air pour une 5090, de la place pour un montage propre, et une façade en bois au lieu des lumières.",
 'CyberPower 1500 VA battery backup': 'Batterie de secours CyberPower 1500' + N + 'VA',
 "A power flicker shouldn't end a game or corrupt a drive. It gives time to save and shut down safely.": "Une micro-coupure ne devrait pas mettre fin à une partie ni corrompre un disque. Ça donne le temps de sauvegarder et d'éteindre en sécurité.",
 'Desk and mounting': 'Bureau et supports',
 'Secretlab top to bottom, so every piece is designed for the desk it sits on.': "Du Secretlab de haut en bas, pour que chaque pièce soit conçue pour le bureau sur lequel elle est installée.",
 'Sit or stand through long sessions, and wide enough for the 57" and everything around it.': "Assis ou debout pendant les longues sessions, et assez large pour le 57" + N + "po et tout ce qui l'entoure.",
 'Motorized sit-stand desk, 1.78 m': 'Bureau assis-debout motorisé, 1,78' + N + 'm',
 'PC off the floor: less dust, and it rises and lowers with the desk.': "Le PC loin du plancher" + N + ": moins de poussière, et il monte et descend avec le bureau.",
 'Holds the PC under the desk': 'Tient le PC sous le bureau',
 'MAGNUS Monitor Arm, Heavy Duty': "Bras d'écran MAGNUS, Heavy Duty",
 'The 57" is heavy. This arm is made to carry it and put it exactly where I want.': "Le 57" + N + "po est lourd. Ce bras est fait pour le porter et le placer exactement où je veux.",
 'For the 57"': 'Pour le 57' + N + 'po',
 '2× MAGNUS Vertical Monitor Stand': "2 supports d'écran verticaux MAGNUS",
 'Holds the top row above the 57" with no holes in the wall, and it moves with the desk.': "Tient la rangée du haut au-dessus du 57" + N + "po sans trous dans le mur, et bouge avec le bureau.",
 'For the top row': 'Pour la rangée du haut',
 'MAGNUS desk mat': 'Tapis de bureau MAGNUS',
 'Protects the desk, steady mouse surface': 'Protège le bureau, surface stable pour la souris',
 'Powered USB hub': 'Concentrateur USB alimenté',
 'Ports within reach, wireless receivers up top': 'Des ports à portée de main, les récepteurs sans fil en hauteur',
 'Headphone hanger': 'Support à casque',
 'Keeps the headset off the desk': 'Garde le casque hors du bureau',
 'Peripherals': 'Périphériques',
 'Wireless where it counts, and nothing that lights up.': "Sans fil là où ça compte, et rien qui s'allume.",
 'Logitech MX Mechanical, full-size': 'Logitech MX Mechanical, pleine grandeur',
 "I want the numpad. Quiet switches so voice chat doesn't hear every key.": "Je veux le pavé numérique. Des interrupteurs silencieux pour que le clavardage vocal n'entende pas chaque touche.",
 'Tactile Quiet switches, white backlight': 'Interrupteurs Tactile Quiet, rétroéclairage blanc',
 'New': 'Nouveau',
 'Comfortable, lots of buttons, and wireless with no lag.': 'Confortable, plein de boutons, et sans fil sans latence.',
 'Wireless, no RGB': 'Sans fil, sans RGB',
 'Headset and mic, bass turned way up': 'Casque et micro, basses montées au maximum',
 'Have it': 'Je l\'ai',
 'Logitech G speakers': 'Haut-parleurs Logitech G',
 'RGB off': 'RGB éteint',
 'Webcam': 'Webcam',
 'Rules of the build': 'Les règles du montage',
 'The principles every part had to pass.': 'Les principes que chaque pièce devait respecter.',
 'No RGB': 'Aucun RGB',
 'Not dimmed, not turned off in software. Parts without it, from the start.': "Pas tamisé, pas éteint dans un logiciel. Des pièces sans RGB, dès le départ.",
 'Quality over price': 'La qualité avant le prix',
 'Built to last for years, not to hit the cheapest total.': "Conçu pour durer des années, pas pour atteindre le total le moins cher.",
 'Checked first': "Vérifié d'abord",
 'Every part verified for compatibility before anything is ordered.': "Chaque pièce vérifiée pour la compatibilité avant de commander quoi que ce soit.",
 'Nothing recycled': 'Rien de recyclé',
 'Every part in the new build is new.': 'Chaque pièce du nouveau PC est neuve.',
 'No last-minute swaps': 'Aucun changement de dernière minute',
 'Once a part is decided, it stays decided.': "Une fois qu'une pièce est choisie, elle reste choisie.",
 'Moves with the desk': 'Bouge avec le bureau',
 'Screens, PC and cables all rise and lower together.': 'Les écrans, le PC et les câbles montent et descendent ensemble.',
 'What I use today': "Ce que j'utilise aujourd'hui",
 'The current PC, still doing its job until the new one is built.': "Le PC actuel, qui fait encore le travail en attendant que le nouveau soit monté.",
 'Intel Core i7-13700K, 16 cores / 24 threads': 'Intel Core i7-13700K, 16 cœurs / 24 fils',
 '32 GB': '32' + N + 'Go',
 'OS': "Système d'exploitation",

 # ---------- ruenix ----------
 'Ruenix MC | TehZombiJesus': 'Ruenix MC | TehZombiJesus',
 'Ruenix MC — a Minecraft network with SMP and SkyPvP servers. How to join, the community, and the staff team.': "Ruenix MC, un réseau Minecraft avec des serveurs SMP et SkyPvP. Comment se joindre, la communauté et l'équipe.",
 'The network I run': 'Le réseau que je gère',
 "I'm the manager of Ruenix, a Minecraft network built around a friendly community. Here's what's coming.": "Je suis le gestionnaire de Ruenix, un réseau Minecraft bâti autour d'une communauté sympathique. Voici ce qui s'en vient.",
 'The servers': 'Les serveurs',
 'Two ways to play today, with more game modes planned.': "Deux façons de jouer aujourd'hui, et d'autres modes de jeu prévus.",
 'Survival multiplayer.': 'Survie multijoueur.',
 'Build, explore, and survive alongside the rest of the community.': 'Construis, explore et survis avec le reste de la communauté.',
 'PvP on floating islands.': 'Du PvP sur des îles flottantes.',
 'Gear up and fight other players across islands in the sky, where one wrong step means a long fall.': "Équipe-toi et affronte d'autres joueurs sur des îles dans le ciel, où un faux pas veut dire une longue chute.",
 "Ruenix isn't open to the public yet. The Discord is the place to be when the doors open.": "Ruenix n'est pas encore ouvert au public. Le Discord, c'est l'endroit où être quand les portes vont ouvrir.",
 '1. Join the Ruenix Discord': '1. Rejoins le Discord de Ruenix',
 '2. Watch the announcements for opening day': "2. Surveille les annonces pour le jour de l'ouverture",
 '3. Grab the server address there and jump in': "3. Prends l'adresse du serveur là-bas et embarque",
 'Community': 'Communauté',
 'The Discord is where everything happens outside the game.': 'Le Discord, c\'est là que tout se passe en dehors du jeu.',
 'English only': 'En anglais seulement',
 'One language': 'Une seule langue',
 'Chat and Discord are in English so everyone can follow along and staff can moderate fairly.': "Le clavardage et le Discord sont en anglais pour que tout le monde puisse suivre et que l'équipe puisse modérer équitablement.",
 'Forums': 'Forums',
 'On Discord': 'Sur Discord',
 'Appeals, bug reports, and suggestions each have their own forum, so nothing gets lost in chat.': "Les appels, les rapports de bogues et les suggestions ont chacun leur propre forum, pour que rien ne se perde dans le clavardage.",
 'Staff team': "L'équipe",
 'Here to help': 'Là pour aider',
 'From Helpers up to the Owner, staff keep the servers fair. Look for the NOX role on Discord.': "Des Helpers jusqu'au propriétaire, l'équipe garde les serveurs équitables. Cherche le rôle NOX sur Discord.",

 # ---------- now ----------
 'Now | TehZombiJesus': 'En ce moment | TehZombiJesus',
 'What TehZombiJesus is up to right now: work, projects, plans and games.': "Ce que fait TehZombiJesus en ce moment" + N + ": travail, projets, plans et jeux.",
 "What I'm up to": 'Ce que je fais',
 "A snapshot of what's keeping me busy these days. If we haven't talked in a while, this is the short version.": "Un aperçu de ce qui m'occupe ces temps-ci. Si on ne s'est pas parlé depuis un bout, voici la version courte.",
 'Updated October 2026.': 'Mis à jour en octobre 2026.',
 'Working on': 'Mes projets',
 'The day-to-day.': 'Le quotidien.',
 'Settling into the CTO and sysadmin role': "Je m'installe dans le rôle de CTO et d'administrateur système",
 'Growing my Discord server and its custom bot, Crypt Keeper': 'Je fais grandir mon serveur Discord et son robot sur mesure, Crypt Keeper',
 'This website': 'Ce site',
 'It keeps learning new tricks. Try the': "Il apprend sans cesse de nouveaux tours. Essaie la touche",
 'key.': '.',
 'Planning': 'En planification',
 'Bought piece by piece, checked twice.': 'Acheté morceau par morceau, vérifié deux fois.',
 'In progress': 'En cours',
 'A 57" super ultrawide with three screens above it, on a sit-stand desk.': "Un super ultralarge de 57" + N + "po avec trois écrans au-dessus, sur un bureau assis-debout.",
 'See the setup': 'Voir le poste de jeu',
 'A homelab rebuild planned in stages, so storage grows without starting over.': 'Une reconstruction du homelab planifiée par étapes, pour que le stockage grandisse sans tout recommencer.',
 'Getting the Minecraft network ready to open its doors to the public.': 'Je prépare le réseau Minecraft à ouvrir ses portes au public.',
 'Playing': 'Mes jeux',
 'Whatever the friends are on, strictly for fun.': 'À quoi les amis jouent, juste pour le plaisir.',
 'League of Legends, ARAM only': 'League of Legends, ARAM seulement',
 "What's a Now page?": "C'est quoi, une page «" + N + "En ce moment" + N + "»" + N + "?",
 'An "about" page tells you who someone is. A "now" page tells you what they\'re focused on at the moment. It\'s an idea started by Derek Sivers, and plenty of people keep one.':
   "Une page «" + N + "à propos" + N + "» dit qui est quelqu'un. Une page «" + N + "en ce moment" + N + "» dit sur quoi la personne se concentre présentement. C'est une idée lancée par Derek Sivers, et beaucoup de gens en ont une.",
 'Read more about it': 'En savoir plus (en anglais)',

 # ---------- 404 ----------
 'Page not found | TehZombiJesus': 'Page introuvable | TehZombiJesus',
 "This page doesn't exist.": "Cette page n'existe pas.",
 'Error 404': 'Erreur 404',
 "This page didn't make it": "Cette page n'a pas survécu",
 'Lost somewhere in the Crypt. The address might be mistyped, or the page has moved.': "Perdue quelque part dans la Crypte. L'adresse est peut-être mal écrite, ou la page a déménagé.",
 'Back to home': "Retour à l'accueil",
}

# ---------- menu additions ----------
FR.update({
 'Devlog': 'Journal',
 'Guestbook': "Livre d'or",
 'Changelog': 'Journal des changements',
 'TehZombiJesus devlog': 'Journal de TehZombiJesus',
 'Devlog | TehZombiJesus': 'Journal | TehZombiJesus',
 'Notes as the TehZombiJesus site, homelab and battlestation come together.': 'Des notes à mesure que le site, le homelab et le poste de jeu de TehZombiJesus prennent forme.',
 'Changelog | TehZombiJesus': 'Journal des changements | TehZombiJesus',
 'Every change to tehzombijesus.ca, from its GitHub history.': "Chaque changement apporté à tehzombijesus.ca, tiré de son historique GitHub.",
})

# ---------- 404 game, Ruenix countdown ----------
FR.update({
 "While you're here": 'Tant qu\'à être ici',
 'Outrun the graveyard. Space, the up arrow or a tap to jump.': 'Échappe au cimetière. Espace, la flèche du haut ou une touche à l\'écran pour sauter.',
 'Crypt Run, a small jumping game': 'Course de la Crypte, un petit jeu de saut',
 'Date to be announced.': 'Date à annoncer.',
})

# ---------- guestbook ----------
FR.update({
 'Guestbook | TehZombiJesus': "Livre d'or | TehZombiJesus",
 'Leave a message in the TehZombiJesus guestbook.': "Laisse un message dans le livre d'or de TehZombiJesus.",
 'Sign the Crypt': 'Signe la Crypte',
 'Old-school web tradition: leave a name and a few words before you go. Messages show up right away, so keep it friendly.':
   "Une tradition du Web d'antan" + N + ": laisse ton nom et quelques mots avant de partir. Les messages apparaissent tout de suite, alors garde ça sympathique.",
 'The guestbook opens soon. The ink is still drying.': "Le livre d'or ouvre bientôt. L'encre sèche encore.",
 'Your name': 'Ton nom',
 'Your message': 'Ton message',
 'No links. Be nice.': 'Pas de liens. Sois gentil.',
 'Sign the guestbook': "Signer le livre d'or",
})


FR.update({ 'Click to copy': 'Clique pour copier' })
